CREATE TABLE Paises (
	id INT PRIMARY KEY,
	codigo VARCHAR(5),
	nombre VARCHAR(50),
	continente VARCHAR(25),
	region VARCHAR(25)
);

INSERT Paises(id, codigo, nombre, continente, region) VALUES (1 ,'ABW', 'Aruba', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (2 ,'AFG', 'Afghanistan', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (3 ,'AGO', 'Angola', 'Africa', 'Central Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (4 ,'AIA', 'Anguilla', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (5 ,'ALB', 'Albania', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (6 ,'AND', 'Andorra', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (7 ,'ANT', 'Netherlands Antilles', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (8 ,'ARE', 'United Arab Emirates', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (9 ,'ARG', 'Argentina', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (10 ,'ARM', 'Armenia', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (11 ,'ASM', 'American Samoa', 'Oceania', 'Polynesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (12 ,'ATA', 'Antarctica', 'Antarctica', 'Antarctica');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (13 ,'ATF', 'French Southern territories', 'Antarctica', 'Antarctica');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (14 ,'ATG', 'Antigua and Barbuda', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (15 ,'AUS', 'Australia', 'Oceania', 'Australia and New Zealand');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (16 ,'AUT', 'Austria', 'Europe', 'Western Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (17 ,'AZE', 'Azerbaijan', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (18 ,'BDI', 'Burundi', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (19 ,'BEL', 'Belgium', 'Europe', 'Western Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (20 ,'BEN', 'Benin', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (21 ,'BFA', 'Burkina Faso', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (22 ,'BGD', 'Bangladesh', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (23 ,'BGR', 'Bulgaria', 'Europe', 'Eastern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (24 ,'BHR', 'Bahrain', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (25 ,'BHS', 'Bahamas', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (26 ,'BIH', 'Bosnia and Herzegovina', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (27 ,'BLR', 'Belarus', 'Europe', 'Eastern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (28 ,'BLZ', 'Belize', 'North America', 'Central America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (29 ,'BMU', 'Bermuda', 'North America', 'North America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (30 ,'BOL', 'Bolivia', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (31 ,'BRA', 'Brazil', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (32 ,'BRB', 'Barbados', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (33 ,'BRN', 'Brunei', 'Asia', 'Southeast Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (34 ,'BTN', 'Bhutan', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (35 ,'BVT', 'Bouvet Island', 'Antarctica', 'Antarctica');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (36 ,'BWA', 'Botswana', 'Africa', 'Southern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (37 ,'CAF', 'Central African Republic', 'Africa', 'Central Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (38 ,'CAN', 'Canada', 'North America', 'North America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (39 ,'CCK', 'Cocos (Keeling) Islands', 'Oceania', 'Australia and New Zealand');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (40 ,'CHE', 'Switzerland', 'Europe', 'Western Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (41 ,'CHL', 'Chile', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (42 ,'CHN', 'China', 'Asia', 'Eastern Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (43 ,'CIV', 'Côte d’Ivoire', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (44 ,'CMR', 'Cameroon', 'Africa', 'Central Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (45 ,'COD', 'Congo, The Democratic Republic of the', 'Africa', 'Central Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (46 ,'COG', 'Congo', 'Africa', 'Central Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (47 ,'COK', 'Cook Islands', 'Oceania', 'Polynesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (48 ,'COL', 'Colombia', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (49 ,'COM', 'Comoros', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (50 ,'CPV', 'Cape Verde', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (51 ,'CRI', 'Costa Rica', 'North America', 'Central America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (52 ,'CUB', 'Cuba', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (53 ,'CXR', 'Christmas Island', 'Oceania', 'Australia and New Zealand');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (54 ,'CYM', 'Cayman Islands', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (55 ,'CYP', 'Cyprus', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (56 ,'CZE', 'Czech Republic', 'Europe', 'Eastern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (57 ,'DEU', 'Germany', 'Europe', 'Western Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (58 ,'DJI', 'Djibouti', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (59 ,'DMA', 'Dominica', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (60 ,'DNK', 'Denmark', 'Europe', 'Nordic Countries');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (61 ,'DOM', 'Dominican Republic', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (62 ,'DZA', 'Algeria', 'Africa', 'Northern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (63 ,'ECU', 'Ecuador', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (64 ,'EGY', 'Egypt', 'Africa', 'Northern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (65 ,'ERI', 'Eritrea', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (66 ,'ESH', 'Western Sahara', 'Africa', 'Northern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (67 ,'ESP', 'Spain', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (68 ,'EST', 'Estonia', 'Europe', 'Baltic Countries');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (69 ,'ETH', 'Ethiopia', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (70 ,'FIN', 'Finland', 'Europe', 'Nordic Countries');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (71 ,'FJI', 'Fiji Islands', 'Oceania', 'Melanesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (72 ,'FLK', 'Falkland Islands', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (73 ,'FRA', 'France', 'Europe', 'Western Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (74 ,'FRO', 'Faroe Islands', 'Europe', 'Nordic Countries');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (75 ,'FSM', 'Micronesia, Federated States of', 'Oceania', 'Micronesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (76 ,'GAB', 'Gabon', 'Africa', 'Central Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (77 ,'GBR', 'United Kingdom', 'Europe', 'British Islands');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (78 ,'GEO', 'Georgia', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (79 ,'GHA', 'Ghana', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (80 ,'GIB', 'Gibraltar', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (81 ,'GIN', 'Guinea', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (82 ,'GLP', 'Guadeloupe', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (83 ,'GMB', 'Gambia', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (84 ,'GNB', 'Guinea-Bissau', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (85 ,'GNQ', 'Equatorial Guinea', 'Africa', 'Central Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (86 ,'GRC', 'Greece', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (87 ,'GRD', 'Grenada', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (88 ,'GRL', 'Greenland', 'North America', 'North America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (89 ,'GTM', 'Guatemala', 'North America', 'Central America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (90 ,'GUF', 'French Guiana', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (91 ,'GUM', 'Guam', 'Oceania', 'Micronesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (92 ,'GUY', 'Guyana', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (93 ,'HKG', 'Hong Kong', 'Asia', 'Eastern Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (94 ,'HMD', 'Heard Island and McDonald Islands', 'Antarctica', 'Antarctica');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (95 ,'HND', 'Honduras', 'North America', 'Central America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (96 ,'HRV', 'Croatia', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (97 ,'HTI', 'Haiti', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (98 ,'HUN', 'Hungary', 'Europe', 'Eastern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (99 ,'IDN', 'Indonesia', 'Asia', 'Southeast Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (100 ,'IND', 'India', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (101 ,'IOT', 'British Indian Ocean Territory', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (102 ,'IRL', 'Ireland', 'Europe', 'British Islands');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (103 ,'IRN', 'Iran', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (104 ,'IRQ', 'Iraq', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (105 ,'ISL', 'Iceland', 'Europe', 'Nordic Countries');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (106 ,'ISR', 'Israel', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (107 ,'ITA', 'Italy', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (108 ,'JAM', 'Jamaica', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (109 ,'JOR', 'Jordan', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (110 ,'JPN', 'Japan', 'Asia', 'Eastern Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (111 ,'KAZ', 'Kazakstan', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (112 ,'KEN', 'Kenya', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (113 ,'KGZ', 'Kyrgyzstan', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (114 ,'KHM', 'Cambodia', 'Asia', 'Southeast Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (115 ,'KIR', 'Kiribati', 'Oceania', 'Micronesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (116 ,'KNA', 'Saint Kitts and Nevis', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (117 ,'KOR', 'South Korea', 'Asia', 'Eastern Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (118 ,'KWT', 'Kuwait', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (119 ,'LAO', 'Laos', 'Asia', 'Southeast Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (120 ,'LBN', 'Lebanon', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (121 ,'LBR', 'Liberia', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (122 ,'LBY', 'Libyan Arab Jamahiriya', 'Africa', 'Northern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (123 ,'LCA', 'Saint Lucia', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (124 ,'LIE', 'Liechtenstein', 'Europe', 'Western Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (125 ,'LKA', 'Sri Lanka', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (126 ,'LSO', 'Lesotho', 'Africa', 'Southern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (127 ,'LTU', 'Lithuania', 'Europe', 'Baltic Countries');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (128 ,'LUX', 'Luxembourg', 'Europe', 'Western Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (129 ,'LVA', 'Latvia', 'Europe', 'Baltic Countries');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (130 ,'MAC', 'Macao', 'Asia', 'Eastern Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (131 ,'MAR', 'Morocco', 'Africa', 'Northern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (132 ,'MCO', 'Monaco', 'Europe', 'Western Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (133 ,'MDA', 'Moldova', 'Europe', 'Eastern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (134 ,'MDG', 'Madagascar', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (135 ,'MDV', 'Maldives', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (136 ,'MEX', 'Mexico', 'North America', 'Central America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (137 ,'MHL', 'Marshall Islands', 'Oceania', 'Micronesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (138 ,'MKD', 'Macedonia', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (139 ,'MLI', 'Mali', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (140 ,'MLT', 'Malta', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (141 ,'MMR', 'Myanmar', 'Asia', 'Southeast Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (142 ,'MNG', 'Mongolia', 'Asia', 'Eastern Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (143 ,'MNP', 'Northern Mariana Islands', 'Oceania', 'Micronesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (144 ,'MOZ', 'Mozambique', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (145 ,'MRT', 'Mauritania', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (146 ,'MSR', 'Montserrat', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (147 ,'MTQ', 'Martinique', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (148 ,'MUS', 'Mauritius', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (149 ,'MWI', 'Malawi', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (150 ,'MYS', 'Malaysia', 'Asia', 'Southeast Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (151 ,'MYT', 'Mayotte', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (152 ,'NAM', 'Namibia', 'Africa', 'Southern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (153 ,'NCL', 'New Caledonia', 'Oceania', 'Melanesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (154 ,'NER', 'Niger', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (155 ,'NFK', 'Norfolk Island', 'Oceania', 'Australia and New Zealand');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (156 ,'NGA', 'Nigeria', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (157 ,'NIC', 'Nicaragua', 'North America', 'Central America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (158 ,'NIU', 'Niue', 'Oceania', 'Polynesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (159 ,'NLD', 'Netherlands', 'Europe', 'Western Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (160 ,'NOR', 'Norway', 'Europe', 'Nordic Countries');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (161 ,'NPL', 'Nepal', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (162 ,'NRU', 'Nauru', 'Oceania', 'Micronesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (163 ,'NZL', 'New Zealand', 'Oceania', 'Australia and New Zealand');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (164 ,'OMN', 'Oman', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (165 ,'PAK', 'Pakistan', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (166 ,'PAN', 'Panama', 'North America', 'Central America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (167 ,'PCN', 'Pitcairn', 'Oceania', 'Polynesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (168 ,'PER', 'Peru', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (169 ,'PHL', 'Philippines', 'Asia', 'Southeast Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (170 ,'PLW', 'Palau', 'Oceania', 'Micronesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (171 ,'PNG', 'Papua New Guinea', 'Oceania', 'Melanesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (172 ,'POL', 'Poland', 'Europe', 'Eastern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (173 ,'PRI', 'Puerto Rico', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (174 ,'PRK', 'North Korea', 'Asia', 'Eastern Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (175 ,'PRT', 'Portugal', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (176 ,'PRY', 'Paraguay', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (177 ,'PSE', 'Palestine', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (178 ,'PYF', 'French Polynesia', 'Oceania', 'Polynesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (179 ,'QAT', 'Qatar', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (180 ,'REU', 'Réunion', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (181 ,'ROM', 'Romania', 'Europe', 'Eastern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (182 ,'RUS', 'Russian Federation', 'Europe', 'Eastern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (183 ,'RWA', 'Rwanda', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (184 ,'SAU', 'Saudi Arabia', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (185 ,'SDN', 'Sudan', 'Africa', 'Northern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (186 ,'SEN', 'Senegal', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (187 ,'SGP', 'Singapore', 'Asia', 'Southeast Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (188 ,'SGS', 'South Georgia and the South Sandwich Islands', 'Antarctica', 'Antarctica');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (189 ,'SHN', 'Saint Helena', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (190 ,'SJM', 'Svalbard and Jan Mayen', 'Europe', 'Nordic Countries');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (191 ,'SLB', 'Solomon Islands', 'Oceania', 'Melanesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (192 ,'SLE', 'Sierra Leone', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (193 ,'SLV', 'El Salvador', 'North America', 'Central America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (194 ,'SMR', 'San Marino', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (195 ,'SOM', 'Somalia', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (196 ,'SPM', 'Saint Pierre and Miquelon', 'North America', 'North America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (197 ,'STP', 'Sao Tome and Principe', 'Africa', 'Central Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (198 ,'SUR', 'Suriname', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (199 ,'SVK', 'Slovakia', 'Europe', 'Eastern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (200 ,'SVN', 'Slovenia', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (201 ,'SWE', 'Sweden', 'Europe', 'Nordic Countries');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (202 ,'SWZ', 'Swaziland', 'Africa', 'Southern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (203 ,'SYC', 'Seychelles', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (204 ,'SYR', 'Syria', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (205 ,'TCA', 'Turks and Caicos Islands', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (206 ,'TCD', 'Chad', 'Africa', 'Central Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (207 ,'TGO', 'Togo', 'Africa', 'Western Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (208 ,'THA', 'Thailand', 'Asia', 'Southeast Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (209 ,'TJK', 'Tajikistan', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (210 ,'TKL', 'Tokelau', 'Oceania', 'Polynesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (211 ,'TKM', 'Turkmenistan', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (212 ,'TMP', 'East Timor', 'Asia', 'Southeast Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (213 ,'TON', 'Tonga', 'Oceania', 'Polynesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (214 ,'TTO', 'Trinidad and Tobago', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (215 ,'TUN', 'Tunisia', 'Africa', 'Northern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (216 ,'TUR', 'Turkey', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (217 ,'TUV', 'Tuvalu', 'Oceania', 'Polynesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (218 ,'TWN', 'Taiwan', 'Asia', 'Eastern Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (219 ,'TZA', 'Tanzania', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (220 ,'UGA', 'Uganda', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (221 ,'UKR', 'Ukraine', 'Europe', 'Eastern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (222 ,'UMI', 'United States Minor Outlying Islands', 'Oceania', 'Micronesia/Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (223 ,'URY', 'Uruguay', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (224 ,'USA', 'United States', 'North America', 'North America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (225 ,'UZB', 'Uzbekistan', 'Asia', 'Southern and Central Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (226 ,'VAT', 'Holy See (Vatican City State)', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (227 ,'VCT', 'Saint Vincent and the Grenadines', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (228 ,'VEN', 'Venezuela', 'South America', 'South America');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (229 ,'VGB', 'Virgin Islands, British', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (230 ,'VIR', 'Virgin Islands, U.S.', 'North America', 'Caribbean');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (231 ,'VNM', 'Vietnam', 'Asia', 'Southeast Asia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (232 ,'VUT', 'Vanuatu', 'Oceania', 'Melanesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (233 ,'WLF', 'Wallis and Futuna', 'Oceania', 'Polynesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (234 ,'WSM', 'Samoa', 'Oceania', 'Polynesia');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (235 ,'YEM', 'Yemen', 'Asia', 'Middle East');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (236 ,'YUG', 'Yugoslavia', 'Europe', 'Southern Europe');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (237 ,'ZAF', 'South Africa', 'Africa', 'Southern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (238 ,'ZMB', 'Zambia', 'Africa', 'Eastern Africa');
INSERT Paises(id, codigo, nombre, continente, region) VALUES (239 ,'ZWE', 'Zimbabwe', 'Africa', 'Eastern Africa');